#DELETE localhost:9090/api/hosts/delete/2

POST http://localhost:9090/api/user/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

> {%
    client.global.set("jwt_token", response.body.token);
%}