name: Build and Push Docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN  }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Accommodation-App-backend
          file: ./Accommodation-App-backend/Dockerfile
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/accommodation-app-backend:latest

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./accommodation-app-frontend
          file: ./accommodation-app-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/accommodation-app-frontend:latest
          build-args: |
            VITE_BACKEND_HOST=backend.local
            VITE_BACKEND_PORT=80
            VITE_BACKEND_BASE_PATH=/api
